db_path = "~/.config/atuin/history.db"
style = "compact"
inline_height = 25
invert = true
update_check = false
sync_frequency = "5m"
show_preview = true
enter_accept = false

session_path = "$HOME/.atuin_session"
key_path = "$HOME/.atuin_key"